name: DPNW-RTRPG
version: 1.0.0-SNAPSHOT
main: com.dpnw.rtrpg.RTRPG
depend:
  - DPP-Core
softdepend:
  - MythicMobs
api-version: 1.19
authors: [ darksoldier1404, Bruce0203, yejunho10 ]
commands:
  rr: