package com.dpnw.rtrpg.enums;

public enum SkillName {
    LEAP_OF_QUEEN("LEAP_OF_QUEEN", "여왕의 도약", SkillType.ACTIVE),
    CONFUSION("CONFUSION", "교란", SkillType.ACTIVE),
    AIR_SLASH("AIR_SLASH", "에어 슬래쉬", SkillType.ACTIVE),
    ANOTHER_WORLD_PERSON("ANOTHER_WORLD_PERSON", "이세계인", SkillType.PASSIVE),
    APPETITE("APPETITE", "식욕", SkillType.PASSIVE),
    BERSERKR("BERSERKR", "베르세르크", SkillType.PASSIVE),
    BETRAYAL("BETRAYAL", "배신", SkillType.PASSIVE),
    BIG_BANG("BIG_BANG", "빅뱅", SkillType.ACTIVE),
    BLOOD_BARRIER("BLOOD_BARRIER", "블러드 배리어", SkillType.ACTIVE),
    BODY_CHECK("BODY_CHECK", "보디 체크", SkillType.ACTIVE),
    BURNING("BURNING", "작화", SkillType.PASSIVE),
    BURST("BURST", "버스트", SkillType.ACTIVE),
    CASTING("CASTING", "영창", SkillType.PASSIVE),
    CHALLENGER("CHALLENGER", "도전자", SkillType.PASSIVE),
    CHARGE_SHOT("CHARGE_SHOT", "차지샷", SkillType.PASSIVE),
    CLAWS_OF_THE_DEVIL("CLAWS_OF_THE_DEVIL", "악마의 발톱", SkillType.ACTIVE),
    CLAY_SHIELD("CLAY_SHIELD", "점토 방패", SkillType.ACTIVE),
    CLOCK_OF_THE_END("CLOCK_OF_THE_END", "종언의 시계", SkillType.ACTIVE),
    COMBAT_MANEUVER("COMBAT_MANEUVER", "전투기동", SkillType.HYBRID),
    COSMIC_DISCERNMENT("COSMIC_DISCERNMENT", "우주적 통찰", SkillType.ACTIVE),
    COUNTERATTACK("COUNTERATTACK", "반격", SkillType.PASSIVE),
    CRADLE_OF_BLOOD("CRADLE_OF_BLOOD", "피의 요람", SkillType.PASSIVE),
    CREED("CREED", "신념", SkillType.ACTIVE),
    CUTTING("CUTTING", "베어가르기", SkillType.ACTIVE),
    CUTTING_BONES("CUTTING_BONES", "골단", SkillType.ACTIVE),
    CUTTING_MEAT("CUTTING_MEAT", "육참", SkillType.ACTIVE),
    DASH("DASH", "순간 가속", SkillType.ACTIVE),
    DEAD_HARD("DEAD_HARD", "데드하드", SkillType.ACTIVE),
    DELIGHT_OF_SLAUGHTER("DELIGHT_OF_SLAUGHTER", "살육의 희열", SkillType.PASSIVE),
    DEMON("DEMON", "악귀", SkillType.PASSIVE),
    DER_FREISCHUTZ("DER_FREISCHUTZ", "마탄의 사수", SkillType.HYBRID),
    DESIRE("DESIRE", "열망", SkillType.PASSIVE),
    DESPAIR_OF_THE_DEAD("DESPAIR_OF_THE_DEAD", "망자의 절망", SkillType.HYBRID),
    DESPERATE_ATTACK("DESPERATE_ATTACK", "필사적인 일격", SkillType.ACTIVE),
    DESTRUCTION("DESTRUCTION", "멸살", SkillType.ACTIVE),
    DEUS_EX_MACHINA("DEUS_EX_MACHINA", "데우스 엑스 마키나", SkillType.HYBRID),
    DOUBLE_JUMP("DOUBLE_JUMP", "2단 점프", SkillType.PASSIVE),
    DRAIN("DRAIN", "흡혈", SkillType.PASSIVE),
    DRUGER("DRUGER", "약쟁이", SkillType.ACTIVE),
    ENDURANCE("ENDURANCE", "인내", SkillType.PASSIVE),
    ENLIGHTENMENT("ENLIGHTENMENT", "깨달음", SkillType.PASSIVE),
    ENVY("ENVY", "질투", SkillType.PASSIVE),
    EVOLUTION("EVOLUTION", "진화", SkillType.PASSIVE),
    EXACTING("EXACTING", "받아내기", SkillType.ACTIVE),
    FIRE_BALL("FIRE_BALL", "파이어 볼", SkillType.ACTIVE),
    FIRE_RING("FIRE_RING", "파이어 링", SkillType.ACTIVE),
    FLASH("FLASH", "점멸", SkillType.ACTIVE),
    FLING_UP("FLING_UP", "올려차기", SkillType.ACTIVE),
    GENOCIDER("GENOCIDER", "제노사이더", SkillType.PASSIVE),
    GLUTTONY("GLUTTONY", "식탐", SkillType.PASSIVE),
    GREED("GREED", "탐욕", SkillType.PASSIVE),
    GREEN_BLOODLINE("GREEN_BLOODLINE", "녹색 핏줄", SkillType.PASSIVE),
    HARDEN("HARDEN", "경화", SkillType.PASSIVE),
    HARD_MUSCLE("HARD_MUSCLE", "단단한 근육", SkillType.PASSIVE),
    HARD_TRAINING("HARD_TRAINING", "지옥훈련", SkillType.ACTIVE),
    HEAD_SHOT("HEAD_SHOT", "헤드샷", SkillType.ACTIVE),
    HEAT_TOLERANCE_1("HEAT_TOLERANCE_1", "내열 1", SkillType.PASSIVE),
    HEAT_TOLERANCE_2("HEAT_TOLERANCE_2", "내열 2", SkillType.PASSIVE),
    HEAT_TOLERANCE_3("HEAT_TOLERANCE_3", "내열 3", SkillType.PASSIVE),
    HIGH_ANGLE_FIRE("HIGH_ANGLE_FIRE", "곡사", SkillType.ACTIVE),
    HIGH_EXISTANCE("HIGH_EXISTANCE", "상위 존재", SkillType.ACTIVE),
    HIT_AND_RUN("HIT_AND_RUN", "치고빠지기", SkillType.ACTIVE),
    HOLINESS("HOLINESS", "신성", SkillType.ACTIVE),
    HORIZON_OF_LIFE("HORIZON_OF_LIFE", "생명의 지평선", SkillType.PASSIVE),
    HUG_OF_WIND("HUG_OF_WIND", "바람의 포옹", SkillType.PASSIVE),
    ICE_EDGE("ICE_EDGE", "아이스 엣지", SkillType.ACTIVE),
    IMMOVABLE("IMMOVABLE", "요지부동", SkillType.ACTIVE),
    IRON_WALL("IRON_WALL", "철벽", SkillType.PASSIVE),
    JET_STOMP("JET_STOMP", "제트 스톰프", SkillType.ACTIVE),
    KEY_OF_THE_TIME("KEY_OF_THE_TIME", "시간의 열쇠", SkillType.HYBRID),
    LEAP("LEAP", "도약", SkillType.ACTIVE),
    LIGHTNING_SPEAR_OF_THE_SUNLIGHT("LIGHTNING_SPEAR_OF_THE_SUNLIGHT", "태양빛 뇌창", SkillType.ACTIVE),
    LUCK("LUCK", "행운", SkillType.PASSIVE),
    LUST("LUST", "음욕", SkillType.PASSIVE),
    MANA_EATER("MANA_EATER", "마나 이터", SkillType.PASSIVE),
    MARCH("MARCH", "진군", SkillType.ACTIVE),
    MEMENTOMORI("MEMENTOMORI", "메멘토모리", SkillType.PASSIVE),
    MEMORY_OF_FEET("MEMORY_OF_FEET", "발의 기억", SkillType.ACTIVE),
    MONSTER("MONSTER", "괴수", SkillType.HYBRID),
    MUDDINESS("MUDDINESS", "질척임", SkillType.PASSIVE),
    NOOB("NOOB", "NOOB", SkillType.ACTIVE),
    OVERHEATING("OVERHEATING", "과열", SkillType.PASSIVE),
    OVERWHELMING_POWER("OVERWHELMING_POWER", "압도적인 힘", SkillType.ACTIVE),
    PARRYING("PARRYING", "패링", SkillType.ACTIVE),
    PASSING_AND_HIT("PASSING_AND_HIT", "흘려치기", SkillType.ACTIVE),
    POISON_TOLERANCE_1("POISON_TOLERANCE_1", "내독 1", SkillType.PASSIVE),
    POISON_TOLERANCE_2("POISON_TOLERANCE_2", "내독 2", SkillType.PASSIVE),
    POISON_TOLERANCE_3("POISON_TOLERANCE_3", "내독 3", SkillType.PASSIVE),
    POUR("POUR", "쇄도", SkillType.ACTIVE),
    PRICE("PRICE", "교만", SkillType.PASSIVE),
    PROMOTER("PROMOTER", "승격자", SkillType.PASSIVE),
    PUNISHMENT("PUNISHMENT", "처형", SkillType.ACTIVE),
    RAPID_GROWTH("RAPID_GROWTH", "급성장", SkillType.PASSIVE),
    RECYCLING("RECYCLING", "재생", SkillType.PASSIVE),
    REINFORCE("REINFORCE", "증강", SkillType.PASSIVE),
    RESOLUTION("RESOLUTION", "결의", SkillType.PASSIVE),
    RESUSCITATION("RESUSCITATION", "기사회생", SkillType.ACTIVE),
    SEVEN_DEADLY_SINS("SEVEN_DEADLY_SINS", "칠죄종", SkillType.HYBRID),
    SHARP_BLADE("SHARP_BLADE", "날카로운 칼날", SkillType.PASSIVE),
    SHOOTING_OUT_SLIME("SHOOTING_OUT_SLIME", "점액 사출", SkillType.ACTIVE),
    SIN("SIN", "죄", SkillType.PASSIVE),
    SLOTH("SLOTH", "나태", SkillType.PASSIVE),
    SOAR("SOAR", "비상", SkillType.ACTIVE),
    SONG_OF_DREAM("SONG_OF_DREAM", "수면의 노래", SkillType.ACTIVE),
    SOUL_OF_ADVENTURER("SOUL_OF_ADVENTURER", "모험가의 혼", SkillType.PASSIVE),
    SOUL_OF_BERSERKER("SOUL_OF_BERSERKER", "광전사의 혼", SkillType.PASSIVE),
    SOUL_OF_EXPLORER("SOUL_OF_EXPLORER", "탐험가의 혼", SkillType.PASSIVE),
    SOUL_OF_GLADIATOR("SOUL_OF_GLADIATOR", "검투사의 혼", SkillType.PASSIVE),
    SPARKLE("SPARKLE", "광채", SkillType.ACTIVE),
    SPIN_ATTACK("SPIN_ATTACK", "회전베기", SkillType.ACTIVE),
    SPIRIT_DASH("SPIRIT_DASH", "망령질주", SkillType.ACTIVE),
    SPRING_OF_LIFE("SPRING_OF_LIFE", "생명의 샘", SkillType.ACTIVE),
    SPRINT("SPRINT", "스프린트", SkillType.ACTIVE),
    STABBING_TO_DEATH("STABBING_TO_DEATH", "척살", SkillType.ACTIVE),
    STAMPING("STAMPING", "짓밟기", SkillType.ACTIVE),
    STOMACH_ACID_FORTIFICATION("STOMACH_ACID_FORTIFICATION", "위산 강화", SkillType.PASSIVE),
    STRIKE("STRIKE", "강타", SkillType.ACTIVE),
    STRONG_ATTACK("STRONG_ATTACK", "강격", SkillType.PASSIVE),
    SUPEREXPLOSION("SUPEREXPLOSION", "대폭발", SkillType.ACTIVE),
    SURVIVOR("SURVIVOR", "살아남은 자", SkillType.PASSIVE),
    SWORD_RAIN("SWORD_RAIN", "소드 레인", SkillType.ACTIVE),
    TENSION("TENSION", "장력", SkillType.PASSIVE),
    THANATOPHOBIA("THANATOPHOBIA", "타나토포비아", SkillType.PASSIVE),
    THE_JUDGEMENT_DAY("THE_JUDGEMENT_DAY", "심판의 날", SkillType.ACTIVE),
    THE_LAST_OF_FOOL("THE_LAST_OF_FOOL", "바보의 최후", SkillType.ACTIVE),
    THREE_STEP("THREE_STEP", "세걸음", SkillType.ACTIVE),
    THRESHOLD_OF_DEATH("THRESHOLD_OF_DEATH", "죽음의 문턱", SkillType.ACTIVE),
    THROE("THROE", "격통", SkillType.PASSIVE),
    TIME_DISTORTION("TIME_DISTORTION", "시간 왜곡", SkillType.ACTIVE),
    TRAINING("TRAINING", "수련", SkillType.ACTIVE),
    TURTLE("TURTLE", "터틀", SkillType.ACTIVE),
    ULTIMATE_SPIRIT_OF_FIGHT("ULTIMATE_SPIRIT_OF_FIGHT", "진 - 투귀", SkillType.ACTIVE),
    UNDEAD("UNDEAD", "불사자", SkillType.PASSIVE),
    UNYIELDINGNESS("UNYIELDINGNESS", "불굴", SkillType.PASSIVE),
    VISCOSITY("VISCOSITY", "점성", SkillType.PASSIVE),
    WAR_CRYING("WAR_CRYING", "전쟁의 외침", SkillType.ACTIVE),
    WATER_BALL("WATER_BALL", "워터 볼", SkillType.ACTIVE),
    WHEEL_ATTACK("WHEEL_ATTACK", "휠 어택", SkillType.ACTIVE),
    WHITE_ARMOR("WHITE_ARMOR", "순백 갑주", SkillType.PASSIVE),
    WHITE_STRIKE("WHITE_STRIKE", "백색 강타", SkillType.ACTIVE),
    WIND_STRIKE("WIND_STRIKE", "윈드 스트라이크", SkillType.ACTIVE),
    WIND_SWORD("WIND_SWORD", "윈드 소드", SkillType.ACTIVE),
    WINGS_OF_THE_DEVIL("WINGS_OF_THE_DEVIL", "악마의 날개", SkillType.ACTIVE),
    WITCH_OF_PLATEAU("WITCH_OF_PLATEAU", "고원의 마녀", SkillType.PASSIVE),
    WRATH("WRATH", "분노", SkillType.PASSIVE),
    METEOR_STRIKE("METEOR_STRIKE", "혜성 강타", SkillType.ACTIVE),
    FAIRWIND("FAIRWIND", "순풍", SkillType.ACTIVE),
    BLESSING_OF_MANA("BLESSING_OF_MANA", "마나의 축복", SkillType.PASSIVE),
    LIGHT_OF_PURIFICATION("LIGHT_OF_PURIFICATION", "정화의 빛", SkillType.ACTIVE),
    ;
    private final String raw;
    private final String kor;
    private final SkillType type;

    SkillName(String raw, String kor, SkillType type) {
        this.raw = raw;
        this.kor = kor;
        this.type = type;
    }

    public String getRaw() {
        return raw;
    }

    public String getKor() {
        return kor;
    }

    public SkillType getType() {
        return type;
    }
}
